cuketmon/src/App.css
=> [fix] 로그인화면- 모바일 반응형 수정

cuketmon/src/menubar/menubar.css
-클래스 이름 수정(기존 클래스 명으로 적으니 다른 css에 영향을 미침)
-메뉴 텍스트 밑줄 제거
-메뉴 텍스트 색깔 변경
=> [fix] 메뉴바- css 수정

cuketmon/src/App.css
=> [fix] 로그인화면- 반응형 오류 수정

cuketmon/src/App.css
-instruction 속 포켓몬 로고 padding 0으로 변경
=> [fix] 로그인화면- 포켓몬 로고 위치 수정

cuketmon/src/App.css
- 버튼 클래스 명 수정 
(기존 클래스 명으로 하면 모든 페이지의 버튼이 해당 css 설정으로 적용이 되는 문제가 발생해 수정했습니다.)
=> [fix] 로그인 페이지- 버튼 수정

cuketmon/src/menubar/menubar.css
=> [fix] 메뉴바- 버튼 테두리 변경

BE/src/main/java/cuketmon/trainer/controller/TrainerController.java, BE/src/main/java/cuketmon/trainer/dto/TrainerDTO.java, BE/src/main/java/cuketmon/trainer/entity/Trainer.java, BE/src/main/java/cuketmon/trainer/repository/TrainerRepository.java, BE/src/main/java/cuketmon/trainer/service/TrainerService.java
=> [feat] Trainer가 지닌 장남감, 먹이 개수 확인 기능 구현

BE/src/main/java/cuketmon/monster/controller/MonsterController.java, BE/src/main/java/cuketmon/monster/dto/MonsterDTO.java, BE/src/main/java/cuketmon/monster/entity/Monster.java, BE/src/main/java/cuketmon/monster/repository/MonsterRepository.java, BE/src/main/java/cuketmon/monster/service/MonsterService.java, BE/src/main/java/cuketmon/trainer/controller/TrainerController.java, BE/src/main/java/cuketmon/trainer/entity/Trainer.java
- 마이페이지에서 사용될 기능 일부 구현
- 이슈 확인! #20
=> [feat] 먹이주기, 놀아주기 기능 구현

cuketmon/src/ranking.js
=> [feat] 랭킹페이지- 기초 작업

cuketmon/src/ranking.css, cuketmon/src/ranking.js
=> [feat] 랭킹페이지- desktop UI/UX 구현

cuketmon/src/ranking.css
-랭킹 보드 padding 수정
-랭킹 보드 margin-top 수정
=> [fix] 랭킹화면- 랭킹 보드 위치 수정

cuketmon/src/mypage.css
=> [feat] 마이페이지- 버튼 눌림 효과 추가

BE/build.gradle, BE/src/main/java/cuketmon/WebClientConfig.java, BE/src/main/java/cuketmon/skill/SkillConfig.java, BE/src/main/java/cuketmon/skill/controller/SkillController.java, BE/src/main/java/cuketmon/skill/dto/AllSkillResponse.java, BE/src/main/java/cuketmon/skill/dto/SkillDTO.java, BE/src/main/java/cuketmon/skill/dto/SkillResponse.java, BE/src/main/java/cuketmon/skill/entity/Skill.java, BE/src/main/java/cuketmon/skill/repository/SkillRepository.java, BE/src/main/java/cuketmon/skill/service/SkillService.java, BE/src/main/resources/application.properties
=> [feat] skill api 받기 및  DB 저장 기능 구현

cuketmon/src/battle.js
=> [fix] 전투화면- 이미지 표시오류

cuketmon/src/App.css
=> [fix] 로그인화면- 버튼 위치 조정

BE/src/main/java/cuketmon/skill/controller/SkillController.java, BE/src/main/java/cuketmon/skill/dto/SkillResponse.java, BE/src/main/java/cuketmon/skill/service/SkillService.java, BE/src/main/java/cuketmon/trainer/repository/TrainerRepository.java, BE/src/main/java/cuketmon/trainer/service/TrainerService.java, BE/src/main/java/cuketmon/type/Type.java, BE/src/main/java/cuketmon/type/TypeDamageTable.java, BE/src/test/java/cuketmon/type/TypeDamageTableTest.java
=> feat: type table 구현

cuketmon/src/MakeResult.css, cuketmon/src/MakeResult.js
=> [feat] 생성결과화면- 애니메이션 구현

cuketmon/src/MakeResult.css, cuketmon/src/MakeResult.js
-생성 실패 시, 멘트 박스를 클릭하면 뒤로 갈 수 있게 구현
=> [feat] 생성결과화면- 커켓몬 제작 실패 처리

cuketmon/src/MakeResult.css
=> [fix] 생성결과화면- 멘트 위치 수정

cuketmon/src/Make.js
=> [fix] 생성페이지-프롬프트 최대 입력 글자수 수정

cuketmon/src/App.css, cuketmon/src/App.js
-버튼 주변 부분을 클릭해도 페이지가 넘어가는 오류 수정
=> [fix] 로그인화면-버튼 클릭 오류 수정

BE/src/main/java/cuketmon/monster/entity/Monster.java, BE/src/main/java/cuketmon/monster/service/MonsterService.java, BE/src/main/java/cuketmon/skill/entity/Skill.java, BE/src/main/java/cuketmon/skill/repository/SkillRepository.java, BE/src/main/java/cuketmon/skill/service/SkillService.java, BE/src/main/java/cuketmon/type/Type.java, BE/src/test/java/cuketmon/skill/service/SkillServiceTest.java
=> [feat] 커켓몬에게 스킬 부여 기능 구현

cuketmon/src/Make/Make.js
-커켓몬 볼 이미지 경로 수정
-기존 <option> 코드 길이 최소화
=> [fix] 생성페이지- 이미지 경로 수정 및 코드 최소화

cuketmon/src/MyPage/MyPage.js
=> [fix] 마이페이지- 디폴트 이미지 삭제

BE/build.gradle, BE/src/main/java/cuketmon/monster/controller/MonsterController.java, BE/src/main/java/cuketmon/monster/dto/NamingDTO.java, BE/src/main/java/cuketmon/monster/entity/Monster.java, BE/src/main/java/cuketmon/monster/repository/MonsterRepository.java, BE/src/main/java/cuketmon/monster/service/MonsterService.java
- 이슈 참고 #71
- 백엔드에서는 커켓몬 이름은 15자 이내로 제한
- 테스트 완료
=> [feat] 커켓몬 이름 짓기 기능 구현

BE/src/main/java/cuketmon/monster/controller/MonsterController.java, BE/src/main/java/cuketmon/monster/dto/NamingDTO.java
=> [fix] 이름은 2자이상, 15자이하로 제한하도록 변경

cuketmon/src/Menubar/Menubar.css, cuketmon/src/MyPage/MyPage.css
-화면이 모바일 세로 길이에 맞게 적용되지 않았던 문제 해결
-반응형 미디어 쿼리 내 최대 사이즈 조정
=> [fix] 마이페이지- mobile 반응형 화면 크기 오류 해결

BE/src/main/java/cuketmon/monster/controller/MonsterController.java, BE/src/main/java/cuketmon/monster/service/MonsterService.java
- FE에서 커켓몬의 id로 request를 보낼 수 있도록 하기 위함
=> [fix] 커켓몬 생성 후 해당 커켓몬의 id를 반환하도록 변경

BE/src/main/java/cuketmon/monster/controller/MonsterController.java, BE/src/main/java/cuketmon/monster/service/MonsterService.java
- 마음에 안드는 커켓몬을 놓아주는 기능 추가
- 이슈 참고 #86
=> [feat] 커켓몬 놓아주기 기능 구현

cuketmon/src/battle.css, cuketmon/src/battle.js
-애니메이션을 어떻게 구현할지 생각하고 코드작성, 아직 이미지 파일 슬라이싱 및 분류 필요
-비효율적인 반복된 코드 제거
-전투 유무를 기준으로 전체 컴포넌트가 변경되는 것보다 필요없는 컴포넌트만 빠져서 표시가 안되게 했음.
=> [feat] 전투화면- 애니메이션 로직

cuketmon/src/MyPage/MyPage.css, cuketmon/src/MyPage/MyPage.js
-삭제 버튼 추가 및 삭제 버튼 반응형 구현
-삭제 버튼 백엔드 연동 기초 작업
=> [feat] 마이페이지- 커켓몬 삭제 버튼 추가

cuketmon/src/Ranking/Ranking.js
=> [feat] 랭킹 페이지- 엔드포인트 추가

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js
- 기술 사용 후 isPlayerHit 와 isEnemyHit 상태로 턴 분리 염두에 두고 피격효과 적용
=> [feat] 전투화면- 피격효과 추가

cuketmon/src/MyPage/MyPage.js
=> [feat] 마이페이지- 엔드포인트 추가

cuketmon/.gitignore, cuketmon/package-lock.json, cuketmon/src/MyPage/MyPage.js
- 깃 이그노어 수정
- 마이페이지 백엔드 연동 기초 작업
=> [feat] 마이페이지- 백엔드 연동 작업

BE/src/main/resources/application.properties, BE/src/test/java/cuketmon/skill/service/SkillServiceTest.java
=> [fix] properties 파일 수정

BE/.gitignore
- 배포 완료 후 application.properties 파일이 업로드 되는 것을 방지
=> [chore] update .gitignore

BE/src/main/java/cuketmon/monster/controller/MonsterController.java, BE/src/main/java/cuketmon/monster/dto/MonsterDTO.java, BE/src/main/java/cuketmon/monster/service/MonsterService.java
- 커켓몬 조회 가능
- 전투용 조회, 마이페이지용 조회 2가지 요청 구현
- 이슈 참고 #106
=> [feat] 커켓몬 조회 기능 구현

cuketmon/src/MyPage/MyPage.js
- 커켓몬 이미지 불러오기 연동 완료
- 커켓몬 이름 불러오기 연동 완료
- 커켓몬 친밀도 불러오기 연동 완료
=> [feat] 마이페이지- 커켓몬 불러오기 연동

cuketmon/src/MyPage/MyPage.js
=> [feat] 마이페이지-키보드 이벤트 재구현

BE/README.md, BE/src/main/java/cuketmon/battle/TeamMaker.java, BE/src/main/java/cuketmon/battle/dto/TrainerRequest.java, BE/src/main/java/cuketmon/battle/service/BattleMatchService.java, BE/src/main/java/cuketmon/damageclass/DamageClass.java, BE/src/main/java/cuketmon/monster/entity/Monster.java, BE/src/main/java/cuketmon/monster/service/MonsterService.java, BE/src/main/java/cuketmon/skill/entity/Skill.java, BE/src/main/java/cuketmon/skill/repository/SkillRepository.java, BE/src/main/java/cuketmon/skill/service/SkillService.java, BE/src/main/java/cuketmon/util/Damage.java, BE/src/test/java/cuketmon/battle/service/BattleMatchServiceTest.java, BE/src/test/java/cuketmon/skill/service/SkillServiceTest.java, BE/src/test/java/cuketmon/util/DamageTest.java
=> [test] damage계산 및 웹소켓 테스트 코드 구현

cuketmon/src/Menubar/Menubar.css, cuketmon/src/Menubar/Menubar.js
- 모바일 메뉴바 height 조절
- 메뉴바 hover 효과 추가
#123
=> [feat] 메뉴바- hover 효과 추가 및 높이 조절

cuketmon/src/MyPage/MyPage.css, cuketmon/src/Ranking/Ranking.css, cuketmon/src/Ranking/Ranking.js
- 마이페이지- overflow: hidden 속성을 빼 화면 크기가 맞지않는 경우 스크롤 해 조정할 수 있도록 함.
- 랭킹 페이지- 배경화면 height 맞지 않는 문제 해결  
#27 #28
=> [fix] 마이페이지, 랭킹 페이지- 반응형 오류 수정

cuketmon/src/Make/Make.css, cuketmon/src/Make/Make.js, cuketmon/src/NamePage/NamePage.css
- 생성페이지의 폰트 크기 증가
- type을 하나만 선택해도 커켓몬을 생성할 수 있도록 함.
- 이름 지정 페이지 ▶ 과 글자 입력 창이 맞지 않았던 문제 수정
#134
=> [fix] 생성 페이지- 텍스트 크기 및 요소 위치 조정

BE/src/main/java/cuketmon/oauth/service/CustomOAuth2UserService.java
- 직전 merge와 연속된 merge로 인해 논리적 오류 발생
- 해당 사항 수정
=> [fix] 연속된 머지로 인해 발생한 로직 오류 수정

cuketmon/src/App.css, cuketmon/src/App.js
- 백엔드, 프론트엔드 카카오 로그인 연동
#로그인화면 구현
=> [feat] 로그인 화면- 카카오 로그인 연동

BE/src/main/java/cuketmon/monster/dto/MonsterDTO.java, BE/src/main/java/cuketmon/monster/entity/Monster.java
- byte[]에서 String으로 변경
- AI에서 base64를 인코딩하여 보내기 때문
=> [fix] image 저장 타입 변경

cuketmon/src/Make/Make.css, cuketmon/src/Make/Make.js, cuketmon/src/NamePage/NamePage.css, cuketmon/src/NamePage/NamePage.js
- 커켓몬 특징 프롬프트 최대 글자 수 35자로 제한
- 기존 구현은 직관적이 못 해서 아쉬웠음. 이를 해결하고자 데려가기 버튼 추가
- 재부화 버튼을 추가해 다시 커켓몬을 생성할 수 있도록함
#134
=> [feat] 생성페이지- 글자 수 조정 및 버튼 추가

BE/src/main/java/cuketmon/SecurityConfig.java, BE/src/main/java/cuketmon/monster/entity/Monster.java, BE/src/main/java/cuketmon/oauth/service/OAuth2SuccessHandler.java, BE/src/main/java/cuketmon/trainer/controller/TrainerController.java
- @AuthenticationPrincipal를 사용하여 현재 사용자를 인식 가능하도록 함
- 이제 이름을 api에 넣을 필요없음
- 보안 up 편리함 up
#149
=> [feat] 소셜 로그인을 기반으로하는 api controller 구현

cuketmon/src/App.js, cuketmon/src/AuthContext.js, cuketmon/src/Make/Make.js, cuketmon/src/Menubar/Menubar.js, cuketmon/src/MyPage/MyPage.js, cuketmon/src/TokenInitializer.js, cuketmon/src/index.js
=> [feat] 로그인화면- 토큰 저장 구현

cuketmon/src/Make/Make.js, cuketmon/src/NamePage/NamePage.js, cuketmon/src/TokenInitializer.js
- 이름 지정 페이지에서 token이 존재할 경우, navigate로 다음 페이지(/make)로 리다이렉트 할 수 있도록 함.
- 불필요한 레거시 코드 제거
=> [feat] 생성화면- 이름 지정 페이지 토큰 설정

cuketmon/src/MyPage/MyPage.js
=> [fix] 마이페이지- 엔드포인트 수정

cuketmon/src/MyPage/MyPage.js
- 사용자 이름 불러오는 코드는 지금 당장 필요 없으므로 삭제
=> [fix] 마이페이지- 코드 삭제

cuketmon/src/NamePage/NamePage.css
=> [fix] 생성화면- 글자 크기 및 이름 입력 창 위치 조절

cuketmon/src/MyPage/MyPage.css
- 배경화면 크기가 맞지 않던 문제 해결
- 버튼 위치 조정
- 커켓몬 프로필 위치 조정
- relese button 위치 조정
=> [fix] 마이페이지- 배경화면 크기 문제 해결

cuketmon/src/MainRoutes.js, cuketmon/src/index.css, cuketmon/src/index.js
- 갑자기 라우팅 오류 생긴거 문제 해결
아 진짜 짜증나게 갑자기 라우팅 오류남 근데 앞으로 App.js 필요 없을 수도 ㅋ
몰라 154번임 ㅇㅇ
=> [fix] routing 문제 해결

cuketmon/src/Make/Make.css, cuketmon/src/NamePage/NamePage.css
- feature 입력 칸이 짤리던 문제 해결
- 커켓몬 이름 입력 창 크기 조절
=> [fix] 생성화면- 요소 위치 조정

cuketmon/src/Make/Make.js
=> [fix] 생성페이지- 엔드포인트 수정

cuketmon/src/Make/Make.js
=> [temp] 임시코드 작성

cuketmon/src/Make/Make.js
=> [fix] 생성화면- 몬스터 볼 이미지 오류 해결

cuketmon/src/Make/Make.js
=> [feat] 생성화면- request body 수정

cuketmon/src/MyPage/MyPage.css
- release button 위치 수정
- 커켓몬 프로필 박스 top 조절
=> [fix] 마이페이지- release button, 커켓몬 프로필 위치 수정

BE/src/main/java/cuketmon/SecurityConfig.java
=> [release] 배포

cuketmon/src/MakeResult/MakeResult.css
- ment의 top을 조정해 제대로 된 위치에 표시되도록 함
=> [feat] 생성결과화면- 글자 위치 조정

cuketmon/src/Make/Make.js
=> [fix] 생성페이지

cuketmon/src/Make/Make.js, cuketmon/src/MakeResult/MakeResult.js
=> [feat] 생성화면- 백엔드 연동

cuketmon/src/Make/Make.js
=> [fix] 생성화면- monsterId 받아오기

cuketmon/src/MakeResult/MakeResult.js
=> [fix] 생성결과화면- 엔드포인트 수정

cuketmon/src/MakeResult/MakeResult.js
=> [fix] 생성결과화면- 코드 수정

cuketmon/src/Make/Make.js
- type1과 type2 중 하나라도 선택되지 않거나, description이 비어 있는 경우에 대해 입력 오류를 처리하는 로직 수정
=> [feature] 생성화면- 타입, 프롬프트 조건 수정

cuketmon/src/Make/Make.js
=> [feat] 생성화면- 주소창 토큰 오류 해결

cuketmon/src/MakeResult/MakeResult.css, cuketmon/src/MakeResult/MakeResult.js
- MakeResult.js에 /makepage라고 적혀있던 오타 정정(/make로 고침)
- MakeResult.css 배경 화면이 맞지 않던 문제 해결
- MakeResult.css 알 위치 조정
#57
=> [fix] 생성화면, 생성결과화면- 주소 수정 및 요소 배치 조정

cuketmon/src/Login/Login.css
- '카카오 로그인으로 시작하기' 버튼 텍스트 오른쪽으로 이동시킴
=> [fix] 로그인화면- 버튼 텍스트 위치 수정

cuketmon/src/MakeResult/MakeResult.css
=> [fix] 생성결과화면- 배경화면 적용 문제 해결

cuketmon/src/Make/Make.js
=> [test] 생성화면- 토큰 삭제 시험

cuketmon/src/MakeResult/MakeResult.css, cuketmon/src/MakeResult/MakeResult.js
=> [fix] 생성결과화면- 코드 구조 개선

cuketmon/src/Make/Make.js, cuketmon/src/MakeResult/MakeResult.js
- Make.js ${API_URL}/monster/generate  헤더에 토큰 추가
- MakeResult.js `${API_URL}/monster/${monsterId}/info` 헤더에 Authorization 추가.
=> [feat] 생성화면, 생성결과화면- 토큰 추가

cuketmon/src/MakeResult/MakeResult.js
=> [fix] 생성결과화면- 변수명 변경

cuketmon/src/MakeResult/MakeResult.css, cuketmon/src/MakeResult/MakeResult.js, cuketmon/src/NamePage/NamePage.js
=> [feat] 생성화면, 이름지정화면- 백엔드 연동 코드 추가

cuketmon/src/NamePage/NamePage.css
=> [fix] 이름지정화면- 커켓몬 이미지 위치 조정

cuketmon/src/NamePage/NamePage.js
- make페이지로 돌아가 다시 커켓몬을 만들 수 있게함.
#134
=> [feat] 이름지정화면- 재부화 기능 추가

cuketmon/src/Make/Make.js
=> [feat] 생성화면- utf-8 적용

cuketmon/src/Make/Make.js
=> [test] 생성화면- 타입 영어 변환

cuketmon/src/Make/Make.js
=> [fix] 생성화면- 타입 삭제

cuketmon/src/NamePage/NamePage.js
- /make?token=${token}로 오타 정정
- 쓸모없는 코드(navigate) 제거
=> [fix] 이름지정화면- 주소 수정

cuketmon/src/MyPage/MyPage.js
=> [feat] 마이페이지- 포켓몬 조회 기능 구현

cuketmon/src/MyPage/MyPage.css, cuketmon/src/MyPage/MyPage.js
- 커켓몬  이름 받아오려는 시도를 함
- 커켓몬 id를 받아오기 위해 코드를 개선함
- 커켓몬 이미지 위치를 조정함.
#105
=> [fix] 마이페이지- 커켓몬 이름, id 조회 오류 해결, 요소 조정

BE/src/main/java/cuketmon/monster/controller/MonsterController.java, BE/src/main/java/cuketmon/monster/embeddable/Affinity.java, BE/src/main/java/cuketmon/monster/entity/Monster.java, BE/src/main/java/cuketmon/monster/service/MonsterService.java, BE/src/main/java/cuketmon/trainer/controller/TrainerController.java, BE/src/test/java/cuketmon/TestDummyDataConfig.java, BE/src/test/java/cuketmon/TestSkillDataConfig.java, BE/src/test/java/cuketmon/battle/service/BattleMatchServiceTest.java, BE/src/test/java/cuketmon/monster/embeddable/AffinityTest.java, BE/src/test/java/cuketmon/monster/service/MonsterServiceTest.java, BE/src/test/java/cuketmon/skill/service/SkillServiceTest.java, BE/src/test/java/cuketmon/trainer/embeddable/FeedTest.java, BE/src/test/java/cuketmon/trainer/embeddable/ToyTest.java, BE/src/test/java/cuketmon/type/TypeDamageTableTest.java, BE/src/test/java/cuketmon/util/DamageTest.java
=> [feat] 친밀도가 올랐을 때 행동 구현

cuketmon/src/Make/Make.css, cuketmon/src/Make/Make.js
=> [fix] 생성화면- 버튼 위치 조정

cuketmon/src/Login/Login.js
=> [fix] 로그인화면- 백엔드 연동 코드 수정

cuketmon/src/Make/Make.js
=> [fix] 생성화면- 백엔드 연동 코드 수정

cuketmon/src/Login/Login.js
=> [test] 로그인화면- 주소창에서 token 제거

cuketmon/src/Login/Login.js
=> [test] 로그인화면- 주소창 토큰 삭제

cuketmon/src/Login/Login.js
=> [fix] 토큰 주소창 제거

cuketmon/src/TokenInitializer.js
=> [fix] 토큰 이니셜라이저 수정

cuketmon/src/MyPage/MyPage.css, cuketmon/src/Ranking/Ranking.css
- 마이페이지 커켓몬 방출 버튼 위치 조정
- 랭킹보드 폰트 크기 조정
=> [fix] 모바일 반응형 세부 조정

BE/src/main/java/cuketmon/monster/controller/MonsterController.java, BE/src/main/java/cuketmon/monster/embeddable/Affinity.java, BE/src/main/java/cuketmon/monster/entity/Monster.java, BE/src/main/java/cuketmon/monster/service/MonsterService.java, BE/src/main/java/cuketmon/prompt/entity/Prompt.java, BE/src/main/java/cuketmon/prompt/repository/PromptRepository.java, BE/src/main/java/cuketmon/prompt/service/PromptService.java, BE/src/main/java/cuketmon/skill/repository/SkillRepository.java, BE/src/main/java/cuketmon/skill/service/SkillService.java, BE/src/main/java/cuketmon/trainer/entity/Trainer.java, BE/src/main/java/cuketmon/type/Type.java, BE/src/test/java/cuketmon/monster/service/MonsterServiceTest.java, BE/src/test/java/cuketmon/skill/service/SkillServiceTest.java, BE/src/test/java/cuketmon/util/DamageTest.java
- ai 서버에서 관측 시간을 줄이기 위해 image가 null임이 보장된 table구현
- type이 null이 들어와도 안전하도록 변경
#207
=> [feat] prompt table 구현

cuketmon/src/Battle/Battle.css
=> [fix] - 전투화면 비율조정

BE/src/main/java/cuketmon/monster/controller/MonsterController.java, BE/src/main/java/cuketmon/monster/entity/Monster.java, BE/src/main/java/cuketmon/monster/service/MonsterService.java, BE/src/main/java/cuketmon/trainer/controller/TrainerController.java, BE/src/main/java/cuketmon/trainer/entity/Trainer.java, BE/src/main/java/cuketmon/trainer/service/TrainerService.java, BE/src/main/resources/application.properties, BE/src/test/java/cuketmon/TestDummyDataConfig.java
- 사용자가 생성한 커켓몬을 id로 반환하는 api 구현
#204
=> [feat] 사용자가 생성한 커켓몬을 확인하는 기능 구현

cuketmon/src/MyPage/MyPage.js
=> [refactor] 마이페이지- 코드 개선

cuketmon/public/index.html
- 프론트에서 HTTPS로 업그레이드하는 메타 태그 추가
=> [feat] index.html 메타테그 추가

cuketmon/public/index.html, cuketmon/src/MyPage/MyPage.js
=> [fix] 마이페이지- 토큰 헤더 추가

cuketmon/src/MyPage/MyPage.js
=> [fix] 마이페이지- 불필요 코드 삭제

cuketmon/src/MyPage/MyPage.js
- 토큰, 몬스터 id, 몬스터 배열 길이가 0인 경우 예외를 처리하도록 함
=> [feat] 마이페이지- 예외 처리 추가

cuketmon/src/MyPage/MyPage.js
-  API 호출 중 중복 호출을 방지하기 위해 isLoadingRef를 사용하여 로딩 상태 관리하는 코드 추가
=> [feat] 마이페이지- 로딩 상태 코드 추가

cuketmon/src/MyPage/MyPage.js
- 처음에 커켓몬 상태와 아이템 정보를 받아오지 못하던 문제해결
=> [fix] 마이페이지- 로딩 무한 루프 해결

cuketmon/src/MyPage/MyPage.js
- fetch전 monsters.length==0 처리 구문 삭제
=> [fix] 마이페이지- fetch 전 예외처리 부분 삭제

cuketmon/src/MyPage/MyPage.js
=> [fix] 마이페이지- 배열 받아오기 수정

cuketmon/src/NamePage/NamePage.css, cuketmon/src/NamePage/NamePage.js
- 모바일 반응형 추가
- 커켓몬 이름 입력창 멘트 변경
- api 엔드포인트 변경
=> [feat] 이름지정페이지- 모바일 반응형 주가

cuketmon/public/index.html
- index.html에 (키보드+마우스 스크롤) 브라우저 확대를 방지하는 코드를 추가함.
=> [feat] 브라우저 확대 방지 설정

BE/src/main/java/cuketmon/trainer/controller/TrainerController.java, BE/src/main/java/cuketmon/trainer/dto/TrainerDTO.java, BE/src/main/java/cuketmon/trainer/entity/Trainer.java, BE/src/main/java/cuketmon/trainer/repository/TrainerRepository.java, BE/src/main/java/cuketmon/trainer/service/TrainerService.java
- 기존 작성한 코드에서 불필요한 코드 제거
issue number #214
=> [feat] 랭킹 시스템 - 개선 

BE/build.gradle, BE/src/main/java/cuketmon/CustomLogger.java, BE/src/main/java/cuketmon/monster/service/MonsterService.java, BE/src/main/java/cuketmon/prompt/service/PromptService.java, BE/src/main/java/cuketmon/skill/service/SkillService.java, BE/src/main/java/cuketmon/trainer/service/TrainerService.java, BE/src/main/java/cuketmon/util/CustomLogger.java, BE/src/main/resources/application.properties, BE/src/main/resources/log4j2-spring.xml
=> [feat] log system 구현

cuketmon/src/Battle/Battle.js, cuketmon/src/MainRoutes.js, cuketmon/src/Menubar/Menubar.js, cuketmon/src/PickScreen/PickScreen.css, cuketmon/src/PickScreen/PickScreen.js
전투진입전 커켓몬 선택하는 화면
API 로 커켓몬 정보 받아오기 필요
=> [feat] - 커켓몬픽창

BE/src/main/java/cuketmon/trainer/controller/TrainerController.java, BE/src/main/java/cuketmon/trainer/service/TrainerService.java
trainer name 인풋 방식에서 로그인 사용자 정보 식별로 변경 하였습니다.
#214
=> [feat] trainer name  방식 변경

cuketmon/src/Ranking/Ranking.js
=> [feat] 랭킹화면- 몬스터 id받아오기 타임아웃 설정

cuketmon/src/MyPage/MyPage.js
- 서버로부터 받은 monsterId 배열이 비어있을시 일정 시간동안 다시 시도하게하는 코드 추가
=> [feat] 마이페이지- 커켓몬 id 배열 재로딩 코드 추가

cuketmon/src/MyPage/MyPage.js
=> [fix] 마이페이지- 커켓몬 조회가 바로 되지않던 문제 해결

BE/src/main/java/cuketmon/trainer/controller/TrainerController.java, BE/src/main/java/cuketmon/trainer/dto/TrainerDTO.java, BE/src/main/java/cuketmon/trainer/entity/Trainer.java, BE/src/main/java/cuketmon/trainer/service/TrainerService.java
랭킹 시스템의 엔드 포인트를 수정
- PosetMapping -> GetManpping 으로 변경
- TrainerService 변수명 변경  (t-> trainer)
- allBattle의 타입을 integer로 변경
#214
=> [feat] 엔드 포인트 수정

cuketmon/src/MyPage/MyPage.js
=> [test] 마이페이지- 새로고침시 토큰이 사라지는 오류 test code

cuketmon/src/index.js
=> [fix] 토큰 이니셜라이저 순서 변경

cuketmon/src/index.js
Reverts pknu-wap/2025-1-Web3-cuketmon#270
=> Revert "[fix] 토큰 이니셜라이저 순서 변경"

cuketmon/src/MyPage/MyPage.js
Reverts pknu-wap/2025-1-Web3-cuketmon#269
=> [revert] 마이페이지- 새로고침시 토큰이 사라지는 오류 test code"

cuketmon/src/MyPage/MyPage.js
Reverts pknu-wap/2025-1-Web3-cuketmon#273
=> [revert] 마이페이지- 토큰 받아오는 코드 수정"

BE/src/main/java/cuketmon/constant/message/ErrorMessages.java, BE/src/main/java/cuketmon/monster/constant/MonsterConst.java, BE/src/main/java/cuketmon/monster/controller/MonsterController.java, BE/src/main/java/cuketmon/monster/service/MonsterService.java, BE/src/main/java/cuketmon/trainer/entity/Trainer.java, BE/src/test/java/cuketmon/monster/service/MonsterServiceTest.java
=> [feat] 일일 최대 커켓몬 생성 횟수 제한 기능 구현 

cuketmon/src/MyPage/MyPage.js, cuketmon/src/TokenInitializer.js
=> [test] 마이페이지- 토큰 받아오기 코드 수정

cuketmon/src/MyPage/MyPage.js, cuketmon/src/TokenInitializer.js
Reverts pknu-wap/2025-1-Web3-cuketmon#277
=> [revert] 마이페이지- 토큰 받아오기 코드 수정"

cuketmon/src/MyPage/MyPage.js
=> [test] 마이페이지- 토큰 받아오기 추가

cuketmon/src/MyPage/MyPage.js
=> [fix] 토큰 받아오기 과정에서 오타 수정

cuketmon/src/MyPage/MyPage.css, cuketmon/src/MyPage/MyPage.js
- 먹이주기, 놀아주기 시 애니메이션 시간 증가
- currentMonsterId를 출력하도록 함
=> [fix] 마이페이지- 백엔드연동 코드 수정

cuketmon/src/MyPage/MyPage.js
- 화면을 스와이프해서 다음 커켓몬을 조회할 수 있도록 함.
=> [feat] 마이페이지-모바일 커켓몬 조회 기능 추가

cuketmon/src/PickScreen/PickScreen.css, cuketmon/src/PickScreen/PickScreen.js
일부 클래스를 스네이크 케이스로 설정하지 않은걸 수정했습니다.
=> [fix] 커켓몬픽업화면 - 클래스명 수정

cuketmon/src/Login/Login.css, cuketmon/src/Make/Make.css, cuketmon/src/MyPage/MyPage.css, cuketmon/src/Ranking/Ranking.css
- 로그인 화면- '카카오로그인으로 시작' 글자가 어긋나던 문제 해결
- 생성화면- '제출하기' 버튼 width 증가 및 폰트 위치 수정
- 랭킹화면- 커켓몬 이미지 크기 조절
- 마이페이지- 먹이주기, 놀아주기 버튼이 서로 바꾸어져있던 문제 해결
#288
=> [fix] 모바일 반응형 디테일 수정

cuketmon/src/PickScreen/PickScreen.js
새로고침시 토큰이 사라지는 경우를 방지하기 위해 토큰이 없을시 localstorage 에서 가져오게 변경했습니다.
=> [fix] 커켓몬픽업창- 새로고침시 토큰 사라짐 문제해결

cuketmon/src/Ranking/Ranking.js
- parseInt를 사용해 정수형으로 받아오도록 함.
=> [fix] 랭킹화면- 승패 여부, 배틀 수 받아오기 코드 개선

BE/src/main/java/cuketmon/trainer/controller/TrainerController.java
=> [feat] 랭킹 시스템 request 제거

cuketmon/src/Battle/Battle.js
- 웹소켓 연동이 안되는 이유를 찾기위해 여러시도를 하다 BE 에서 해결을 해 다시 초기 연동코드로 롤백.
=> [fix] 전투화면- 웹소켓연동 롤백

cuketmon/src/Make/Make.js
- make화면 로딩시 첫번째 커켓몬 타입이 '불꽃'으로 초기화 되어있던 문제 해결
=> [fix] 생성화면- 커켓몬 타입 자동 설정 문제 해결

BE/src/main/java/cuketmon/battle/controller/BattleWebSocketController.java, BE/src/main/java/cuketmon/battle/service/BattleMatchService.java, BE/src/main/java/cuketmon/config/SecurityConfig.java, BE/src/main/java/cuketmon/trainer/controller/TrainerController.java
- 웹 소켓 사용에 필요한 api 개발
- 웹 소켓 보안 설정
#290
=> [feat] 웹소켓 관련 설정 추가

cuketmon/src/Battle/Battle.js
- 트레이너 이름을 받아오는 API 가 전투에는 없었는데 트레이너 이름이 필요한 로직이 있었음
=> [feat] 전투화면- 연동/매칭전 트레이너 이름 받아오기

cuketmon/src/NamePage/NamePage.js
- 뒤로가기로인해 원하지 않는 커켓몬이 마이페이지로 무단침입하는 것을 방지함
- 뒤로가기를 막는 logic을 추가함.
=> [fix] 이름지정화면- 뒤로가기로인한 강제 커줍 해결

BE/src/main/java/cuketmon/monster/service/MonsterService.java, BE/src/main/java/cuketmon/oauth/service/OAuth2SuccessHandler.java
- 로컬 테스트 가능하게 변경
- strip() 을 사용해서 앞뒤 공백 제거
=> [fix] DB저장 시 공백제거 및 로컬 테스트가 용이하도록 변경

cuketmon/package-lock.json, cuketmon/package.json
- 잘못된 경로로 설치한 파일 지우고 다시 올바르게 재설치
=> [fix] 전투화면- 웹소켓 모듈 재설치

cuketmon/src/Battle/Battle.js
- api 연동 엔드포인트를 잘못잡아 다시 설정했습니다..
=> [fix] 전투화면- 엔드포인트 재설정

cuketmon/src/PickScreen/PickScreen.js
- 타입하나인 커켓몬은 type2 도 and 로 없으면 컴포넌트 로드가 안되는 부분 고침
- battle 로 monsterId 를 주는데 코드 살짝 고침
=> [fix] 커켓몬픽화면- 타입 하나인 커켓몬 표시/Battle로 monsterId 전송

cuketmon/src/NamePage/NamePage.js
- 뒤로가기가 1번 클릭했을때만 막아지고 그 이후로는 막아지지 않던 문제해결
#309
=> [fix] 이름지정화면- 뒤로가기 금지

cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- 받아온 monsterId 제대로 읽게 수정

cuketmon/src/NamePage/NamePage.js
=> [fix] 이름지정화면- 뒤로가기 금지 코드

BE/src/main/java/cuketmon/monster/controller/MonsterController.java, BE/src/main/java/cuketmon/monster/service/MonsterService.java, BE/src/main/java/cuketmon/oauth/service/OAuth2SuccessHandler.java, BE/src/main/java/cuketmon/prompt/service/PromptService.java, BE/src/main/resources/application.properties, BE/src/test/java/cuketmon/battle/service/BattleMatchServiceTest.java
=> [feat] 남은 프롬프트 개수를 반환하는 로직 구현

cuketmon/src/NamePage/NamePage.js
=> [test] 이름지정화면- 뒤로가기 금지 테스트 코드

cuketmon/src/NamePage/NamePage.js
=> [fix] 이름지정화면- 뒤로가기 후 버튼클릭 문제 해결

cuketmon/src/NamePage/NamePage.js
- 뒤로가기 로직 개선으로 기존 오류(버튼이 클릭되어도 화면이 이동되지않던 오류) 해결
=> [fix] 이름지정화면- 버튼 클릭 오류 해결

cuketmon/src/Make/Make.js, cuketmon/src/MakeResult/MakeResult.js
- eta를 출력하도록 해 사용자의 대기를 도움
#325
=> [feat] 생성화면-eta 연동(1)

cuketmon/src/Make/Make.js
=> [fix] 생성화면- eta 패치 오류 해결

cuketmon/src/Make/Make.js
Reverts pknu-wap/2025-1-Web3-cuketmon#327
=> [revert ] 생성화면- eta 패치 오류 해결"

cuketmon/src/Make/Make.js
=> [fix] 생성화면-eta integerfh 받아오기

cuketmon/src/Make/Make.js
- 이전에 까먹고 고치지않았던 etaData.eta를 etaData로 변경
=> [test] 생성화면- eta integer로 받아오기

cuketmon/src/Make/Make.js
=> [fix] 생성화면- 에타 로직 변경

cuketmon/src/Make/Make.js
=> [test] 생성화면- eta 콘솔코드 추가

cuketmon/src/MakeResult/MakeResult.js
=> [test] 생성결과화면- eta 임시코드 추가

cuketmon/src/MakeResult/MakeResult.js
=> [test] 생성결과화면- 에타 로직 수정

cuketmon/src/MakeResult/MakeResult.js
=> [fix] 생성화면- 이미지 로딩시 바로 NamePage로 이동하게 전환

cuketmon/src/MakeResult/MakeResult.js
- fetchData를 가장 먼저하고 대기시간을 출력하는걸 추후에 하기로 함
=> [fix] 생성화면- 순서변경

cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- 매칭 오류 해결시도

AI/bentoML/service.py, AI/bentoML/test.py, AI/model_inferrence.py, AI/server/config.py, AI/server/inference.py, AI/server/main.py
- BentoML로 모델 서빙
- GPU 2개 사용
- inference time 줄이기 위해 num_inference_steps 50 → 25로 줄임
287
=> 287 feat model serving

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js
- responce 가 tranername 과 opponent 로 값을 주는걸 확인하고 수정
=> [fix] 전투화면- 전투화면 렌더링 안되는 문제 해결시도

cuketmon/src/Make/Make.js, cuketmon/src/MakeResult/MakeResult.js
- 대기 시간을 받고 대기시간을 출력하는 로직을 삭제함
=> [fix] eta 로직 삭제

cuketmon/src/Make/Make.css, cuketmon/src/MyPage/MyPage.css
=> [fix] 반응형 디테일 조정

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js
- API 엔드포인트와 오고가는건 아직 모르지만 조금 만들어둠
=> [feat] 전투화면- 스킬사용 껍데기구현

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js
=> [feat] 전투화면- 전투화면 디테일 조정

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js, cuketmon/src/PickScreen/PickScreen.js
=> [feat] 전투화면- 전투화면 스킬사용 연동

BE/src/main/java/cuketmon/battle/controller/BattleWebSocketController.java, BE/src/main/java/cuketmon/battle/dto/MatchResponse.java, BE/src/main/java/cuketmon/battle/service/BattleMatchService.java
- 자신과 만나는 현상 수정
- 배틀 웹소켓 경로 수정
#348
=> [fix] 배틀 경로 변경 및 오류 수정

cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- 연동 시도

cuketmon/src/Battle/AnimationMap.js, cuketmon/src/Battle/Battle.js
=> [feat] 전투화면- 코드정리

cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- monsterID/trainerName 중 놓친거잡기

cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- trainerName 불러오기 타이밍 문제

cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- console.log 추가

cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- matchResponce 받아오기 수정

cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- 클래스명,변수,로직 대규모 수정

cuketmon/src/Battle/Battle.js
- 코드 수정 중에 상대측에게도 내가 쏘는 애니메이션을 쏴줘야하는데 animationMap 에서 타입과 데미지 클래스에 따라 매핑하는걸 또 하기보단 사용한 animationUrl 을 서버에 주면 서버가 상대한테도 쏴줘서 그걸 받아서 쓰는건 어떤가 싶습니당. . .
=> [fix] 전투화면- 주석처리 및 콘솔로그/서버와 통신에 애니메이션 url 추가

cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- 로딩화면 스피너 클래스 추가

cuketmon/src/Battle/Battle.js
- isMatched 변수로 매칭이 되면 추가 요청이 안가게 했습니다ㅏ..
=> [fix] 전투화면- 매칭요청 중복전송 수정

cuketmon/src/Battle/Battle.js
- isMatched 는 팀원들 의견을 들어보니 불필요한 변수같아 삭제했습니다. . .
- onConnect 시 한번만 실행되도록 해 배틀 요청이 한번만 가게 했습니다. 
- 자신의 trainerName 과 일치하는 matchResponse 를 받으면 구독해둔걸 취소합니다 . . .
=> [fix] 전투화면- 매칭요청 논리오류 해결

cuketmon/src/Battle/Battle.js
- turn 결정은 오로지 BE에 맡겼습니다.
- PP 정보 역시 BE에.
- 의존성배열에 의미없는 const 들이 들어있어 삭제
=> [fix] 전투화면- 회의 후 지적사항 수정

cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- 의존성배열 수정

BE/src/main/java/cuketmon/skill/dto/SkillResponse.java, BE/src/main/java/cuketmon/skill/entity/Skill.java, BE/src/main/java/cuketmon/skill/service/SkillService.java, BE/src/test/java/cuketmon/config/TestSkillDataConfig.java
- 한국어 기술명과 기술 우선순위를 추가로 가져옴
- 커켓몬 배틀에 사용할 예정
#364
=> [fix] skill이 더 많은 정보를 가져오도록 수정

cuketmon/src/MakeResult/MakeResult.js, cuketmon/src/NamePage/NamePage.js
- cuketmonImage로 하니 마이페이지의 커켓몬 이미지를 저장하는 변수와 겹치는 문제 발생
=> [fix] 생성화면- 로컬스토리지 저장 변수명 수정

cuketmon/src/MakeResult/MakeResult.js
- localStorage에서 MakeResultMonsterId를 받아왔어야했는데 monsterId를 받아와 발생하던 오류 해결
=> [fix] 생성결과화면- 변수명 수정

cuketmon/src/Make/Make.css, cuketmon/src/MyPage/MyPage.css, cuketmon/src/MyPage/MyPage.js
- 마이페이지: 버튼 텍스트 줄 나뉨 현상 해결
- 생성화면: 버튼 위치 수정
=> [fix] 반응형 추가 수정 및 불필요한 코드 제거

cuketmon/src/AuthContext.js, cuketmon/src/Login/Login.js, cuketmon/src/Make/Make.js, cuketmon/src/MakeResult/MakeResult.js, cuketmon/src/MyPage/MyPage.js, cuketmon/src/NamePage/NamePage.js, cuketmon/src/Ranking/Ranking.js
=> [fix] token이슈 해결

cuketmon/src/Login/Login.js, cuketmon/src/Make/Make.js
=> [test] 토큰 확인용 코드 추가

cuketmon/src/Login/Login.js
=> [test] 토큰 테스트 코드 추가

cuketmon/src/Login/Login.js, cuketmon/src/Make/Make.js, cuketmon/src/index.js
=> [fix] 토큰 실행 순서 변경

cuketmon/src/Make/Make.js, cuketmon/src/MyPage/MyPage.js, cuketmon/src/Ranking/Ranking.js
=> [test] 토큰 가져오는 코드 임의 추가

cuketmon/src/AuthContext.js, cuketmon/src/Make/Make.js, cuketmon/src/TokenInitializer.js
- access token을 AuthContext에서 accestoken으로 받아오던 오타 수정
=> [fix] 토큰 변수 오타 수정

cuketmon/src/MyPage/MyPage.js
=> [feat] 마이페이지- 커켓몬 방출 시 재확인 메시지 추가

BE/src/main/java/cuketmon/battle/config/WebSocketEventListener.java, BE/src/main/java/cuketmon/battle/constant/BattleConst.java, BE/src/main/java/cuketmon/battle/constant/BattleResult.java, BE/src/main/java/cuketmon/battle/controller/BattleWebSocketController.java, BE/src/main/java/cuketmon/battle/dto/BattleDTO.java, BE/src/main/java/cuketmon/battle/dto/EndBattleResponse.java, BE/src/main/java/cuketmon/battle/dto/MatchResponse.java, BE/src/main/java/cuketmon/battle/dto/SkillRequest.java, BE/src/main/java/cuketmon/battle/repository/ActiveBattles.java, BE/src/main/java/cuketmon/battle/repository/WaitingQueue.java, BE/src/main/java/cuketmon/battle/service/BattleMatchService.java, BE/src/main/java/cuketmon/battle/service/BattleSkillService.java, BE/src/main/java/cuketmon/battle/util/TeamMaker.java, BE/src/main/java/cuketmon/monster/dto/MonsterDTO.java, BE/src/main/java/cuketmon/skill/service/SkillService.java, BE/src/test/java/cuketmon/battle/service/BattleMatchServiceTest.java
- 두 클라이언트가 스킬을 보내고, 두 요청이 모두 도착하면 데미지 주고받기
- 이슈 참고
#374
=> [fix] 커켓몬 배틀 로직 변경

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- 경로설정문제

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- accessToken 으로 수정

cuketmon/package.json, cuketmon/src/Make/Make.css, cuketmon/src/MyPage/MyPage.css, cuketmon/src/common/TypeTable/TypeTable.css
- package.json을 수정해 윈도우에서 npm start가 되지않았던 문제 해결
- typetable: top 수정 및 이미지 크기 변화, 제목 중앙 정렬 설정,모바일 반응형 설정 완료
- 마이페이지: 반응형 배경화면 깨짐 이슈 해결
=> [fix] type별 상성표 css 수정 및 반응형 화면 깨짐 오류 수정

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js
=> [fix] 로딩스크린 어긋남 / 전투화면 콘솔로그 추가

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- 구독 디버깅 콘솔로그 추가

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- 로딩창 css 수정

cuketmon/src/Battle/Battle.js, cuketmon/src/common/TextBox/BattleChatbox.js
=> [fix] 전투화면- 관전이슈 해결

cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- 구독경로수정

cuketmon/src/MakeResult/MakeResult.css, cuketmon/src/MakeResult/MakeResult.js
=> [fix] 생성결과화면- textbox 요소 젼경

BE/src/main/java/cuketmon/battle/config/WebSocketEventListener.java, BE/src/main/java/cuketmon/battle/controller/BattleWebSocketController.java, BE/src/main/java/cuketmon/battle/dto/EndBattleRequest.java, BE/src/main/java/cuketmon/battle/dto/SkillRequest.java, BE/src/main/java/cuketmon/battle/repository/ActiveBattles.java, BE/src/main/java/cuketmon/battle/service/BattleMatchService.java, BE/src/main/java/cuketmon/battle/service/BattleSkillService.java
- 배틀을 종료하는 방식 변경
- 배틀 탈주 감지 기능 구현
#410
=> [fix] 배틀 종료 로직 변경

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- hp0 시 BE로 전송, 컴포넌트 로딩 문제 디버깅

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js
Reverts pknu-wap/2025-1-Web3-cuketmon#412
=> Revert "[fix] 전투화면- hp0 시 BE로 전송, 컴포넌트 로딩 문제 디버깅"

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- 애니메이션 및 피격효과 수정

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- 애니메이션 방향수정

cuketmon/src/MyPage/MyPage.css, cuketmon/src/MyPage/MyPage.js
=> [fix] 마이페이지- 아이템 위치 조정

cuketmon/src/MyPage/MyPage.css
- 일부 기기에서 아이템 재고량이 표시되지 않던 문제 해결
=> [fix] 마이페이지- 아이템 표기 위치 조정

BE/src/main/java/cuketmon/trainer/repository/TrainerRepository.java, BE/src/main/java/cuketmon/trainer/service/TrainerService.java
기존에 있던 불필요한 전체 랭킹 시스템을 제거 후
개별 랭킹 시스템 구조를 개선하였습니다.
#214
=> [fix] 랭킹 시스템- 구조 개선

BE/src/main/java/cuketmon/trainer/entity/Trainer.java, BE/src/main/resources/log4j2-spring.xml
- LocalDateTime 관련 함수는 JVM의 시간을 가져와서 헷갈림
- 한국 시간을 가져오도록 지정 하여 해결
#415
=> [fix] 한국의 시간을 가져오도록 수정

BE/src/main/java/cuketmon/monster/constant/MonsterConst.java, BE/src/main/java/cuketmon/monster/service/MonsterService.java, BE/src/main/java/cuketmon/trainer/embeddable/Feed.java, BE/src/main/java/cuketmon/trainer/embeddable/Toy.java, BE/src/main/java/cuketmon/trainer/service/TrainerService.java, BE/src/test/java/cuketmon/monster/service/MonsterServiceTest.java
=> [fix] 친밀도, 장난감, 먹이 증가 로직 변경

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js
=> [fix] 결과화면- 결과 표시시 자신의 커켓몬 이미지만 표시

cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- type 에러

cuketmon/src/Battle/Battle.js
=> [fix] 전투화면-  ?제거

cuketmon/src/Battle/Battle.js
=> [fix] animationUrl 전송

cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- hp0시 전투종료

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js
=> [feat] 전투화면- 배틀메시지

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js
=> [fix] 전투화면- 경로수정

cuketmon/src/Battle/Battle.js
=> [fix] 배틀메시지 요청 및 습득

cuketmon/src/MyPage/MyPage.js
=> [fix] 마이페이지- 키보드 방향키 전환시, 아이템 갱신 문제 해결

cuketmon/src/MyPage/MyPage.js
Reverts pknu-wap/2025-1-Web3-cuketmon#441
=> [Revert] 마이페이지- 키보드 방향키 전환시, 아이템 갱신 문제 해결"

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js, cuketmon/src/PickScreen/PickScreen.css, cuketmon/src/PickScreen/PickScreen.js
=> [fix] 전체적인 css 수정

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js, cuketmon/src/PickScreen/PickScreen.js
=> [feat] 전투화면- 커켓몬 위치에 따라 동적으로 애니메이션 위치

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js, cuketmon/src/common/HpBar/HpBar.js, cuketmon/src/common/TextBox/BattleChatbox.js
=> [fix] 전투화면- 지적사항 반영

BE/src/main/java/cuketmon/oauth/Controller/RefreshTokenController.java, BE/src/main/java/cuketmon/oauth/controller/AuthController.java, BE/src/main/java/cuketmon/oauth/service/OAuth2SuccessHandler.java, BE/src/main/java/cuketmon/oauth/util/JwtUtil.java, BE/src/main/java/cuketmon/trainer/entity/Trainer.java, BE/src/main/java/cuketmon/trainer/repository/TrainerRepository.java
새로 생성한 package 있어 pr합니다 
refresh token을 통한 access token  재발행 로직을 구현합니다.
누락한 token 서버 저장 로직을 추가합니다.
#209
=> [feat] refreshtoken 재발행 구현

cuketmon/package-lock.json, cuketmon/package.json, cuketmon/src/AuthContext.js
Reverts pknu-wap/2025-1-Web3-cuketmon#448
=> Revert "[feat] 로그인화면- refresh token 로직 구현"

BE/src/main/java/cuketmon/oauth/util/JwtUtil.java
access token = 2분
refresh token = 3시간
=> [fix]토큰 발급 시간 단축

cuketmon/src/Battle/Battle.css, cuketmon/src/common/TextBox/BattleChatbox.css
=> [feat] 전투화면- 반응형

cuketmon/src/AuthContext.js
- 백엔드에서 ms단위로 만기시간을 설정해둔 경우에 맞춰서 코드 수정
=> [fix] refreshToken 만기시간 단위 변경

cuketmon/src/AuthContext.js
=> [fix] refreshToken 만기시간 단위 수정

cuketmon/src/AuthContext.js
- refreshToekn을 바탕으로 accessToken을 받아오는 엔드포인트 수정
- method 변경
=> [fix] refreshToken 엔드포인트 수정

cuketmon/src/AuthContext.js
- json에서 String으로 타입을 받아오도록 수정함.
=> [fix]accesstoken 재발급 타입 수정

cuketmon/src/AuthContext.js
=> [fix] 리프래시토큰 엔포 수정

cuketmon/src/AuthContext.js, cuketmon/src/Login/Login.js, cuketmon/src/TokenInitializer.js
- 로그인하며 refreshToken을 수령할 수 있게 변경함.
- 쓸모없는 console 코드 제거
- 주석 설명 보강
=> [fix] 리프래시토큰 로직 변경

BE/src/main/java/cuketmon/oauth/util/JwtUtil.java
=> [fix] 테스트용으로 설정해준 토큰 유효기간을 복구함

BE/src/test/java/cuketmon/battle/service/BattleMatchServiceTest.java
- Primary를 지정하여 유니크한 조회가 가능하도록 명시함
=> [fix] 테스트 코드 스프링 빈 조회 오류 해결

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js, cuketmon/src/PickScreen/PickScreen.css, cuketmon/src/common/TextBox/SkillDetail.js
=> [feat] 전투화면- css 수정

cuketmon/src/Battle/Battle.css, cuketmon/src/Battle/Battle.js, cuketmon/src/PickScreen/PickScreen.css, cuketmon/src/PickScreen/PickScreen.js, cuketmon/src/common/HpBar/HpBar.js
=> [fix] 전투화면- 타입표시, 버튼 수정

cuketmon/src/PickScreen/PickScreen.css
=> [fix] 선택화면- 버튼 위치조정

BE/src/main/java/cuketmon/battle/service/BattleMatchService.java, BE/src/main/java/cuketmon/battle/service/BattleSkillService.java, BE/src/main/java/cuketmon/monster/service/MonsterService.java, BE/src/main/resources/application.properties
- cpu 매칭 구현
- 로컬 로그인 구현
- 브랜치가 조금 이상해졌는데 괜찮을 겁니다
#472
=> [release] 테스트 서버 배포 및 cpu매칭 구현

BE/src/main/java/cuketmon/oauth/service/CustomOAuth2UserService.java, BE/src/main/java/cuketmon/trainer/repository/TrainerRepository.java
=> [fix] 사용자 이름 저장 방식 변경

cuketmon/src/PickScreen/PickScreen.css
- 미디어 쿼리 max-width 변경
- 버튼 margin-bottom 변경
- 커켓몬 이미지 크기 조정
=> [fix] 픽업화면- 버튼 위치 조정 및 커켓몬 이미지 크기 조정

cuketmon/src/PickScreen/PickScreen.css, cuketmon/src/PickScreen/PickScreen.js, cuketmon/src/common/HpBar/HpBar.css, cuketmon/src/common/HpBar/HpBar.js, cuketmon/src/common/TextBox/BattleChatbox.css
=> [fix] 타입 얼라인 모바일에서 버튼 안눌리는 현상 수정 .. etc
